#!/bin/bash
# This import works for the default WorldCard mobile app format
# Setup gdrive before running this command
# See https://github.com/prasmussen/gdrive
case $1 in

'list')

IFS=$'\n'

files=()
output=()
recurse() {
  files=$(gdrive list --query "trashed = false and fileExtension='csv'" --order 'createdTime desc' --no-header)
  for file in $files
  do
    # id<whitespace>name<whitespace>size
    # splitting things
    id=$(awk '{print $1}' <<< $file | sed -e 's/ //g')
    #id=${id:0,1} #substring

    name=$(awk '{print $2}' <<< $file)
    #types=$(awk '{print $3}' <<< $file)
    size=$(awk '{print $4}' <<< $file)
    created=$(awk '{print $6,$7}' <<< $file)

    output+=("$id;$name;$created")
  done
}
recurse

printf -- '%s\n' "${output[@]}"

;;
'dl')
try=$( gdrive download -f --stdout $2 )
echo $try
if [[ $try == *"is a google document and must be exported"* ]]; then
  echo "Google document!"
  cd $3
  echo $3
  gdrive export -f $2
  ls -al
else
  gdrive download -f --stdout $2 > $3/latest.csv
fi

;;
esac
