#!/bin/bash
# This import works for the default WorldCard mobile app format
# Setup gdrive before running this command
# See https://github.com/prasmussen/gdrive
case $1 in

'list')

IFS=$'\n'

files=()
output=()
recurse() {
  files=$(gdrive list --query "trashed = false and fileExtension='csv'" --order 'createdTime desc' --no-header)
  for file in $files
  do
    # id<whitespace>name<whitespace>size
    # splitting things
    id=$(awk '{print $1}' <<< $file | sed -e 's/ //g')
    #id=${id:0,1} #substring

    name=$(awk '{print $2}' <<< $file)
    #types=$(awk '{print $3}' <<< $file)
    size=$(awk '{print $4}' <<< $file)
    created=$(awk '{print $6,$7}' <<< $file)

    output+=("$id;$name;$created")
  done
}
recurse

printf -- '%s\n' "${output[@]}"

;;
'dl')
gdrive download -f --stdout $2 > $3
;;
esac
